// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace RSO.Core.UserModels;

public partial class UserServicesRSOContext : DbContext
{
    public UserServicesRSOContext(DbContextOptions<UserServicesRSOContext> options)
        : base(options)
    {
    }

    public virtual DbSet<User> User { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("commerceuser_pkey");

            entity.Property(e => e.UserId).UseIdentityAlwaysColumn();
            entity.Property(e => e.UserCity).HasDefaultValueSql("'Ljubljana'::character varying");
            entity.Property(e => e.UserZipCode).HasDefaultValueSql("'1000'::character varying");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}