// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RSO.Core.UserModels;

public partial class User
{
    [Key]
    public int UserId { get; set; }

    [Required]
    [StringLength(100)]
    public string UserName { get; set; }

    [Required]
    [StringLength(200)]
    public string UserEmail { get; set; }

    [Required]
    [StringLength(300)]
    public string UserPassword { get; set; }

    [Required]
    [StringLength(300)]
    public string UserAddress { get; set; }

    [StringLength(5)]
    public string UserZipCode { get; set; }

    [StringLength(100)]
    public string UserCity { get; set; }

    public DateTime? RegisteredOn { get; set; }
}