name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: RSOUserMicroServiceAPI/
        push: true
        tags: muchacho3alex/rsouserservice:latest
        file: RSOUserMicroServiceAPI/RSOUserMicroService/Dockerfile